AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub OIDC Provider and Role for GitHub Actions'

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization/user name
    Default: me2resh

  RepositoryName:
    Type: String
    Description: GitHub repository name
    Default: aws-sam-typescript-bootstrap

  OIDCProviderArn:
    Type: String
    Description: ARN of the GitHub OIDC Provider
    Default: ''

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - "6938fd4d98bab03faadb97b34396831e3780aea1"

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-github-actions-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubOrg}/${RepositoryName}:*'
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

Outputs:
  RoleARN:
    Description: ARN of the IAM role
    Value: !GetAtt GitHubActionsRole.Arn 