# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "patients-appointments-api"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
stack_name = "patients-appointments-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "patients-appointments-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "patients-appointments-api-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "patients-appointments-api-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
image_repositories = []

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "patients-appointments-api-staging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "patients-appointments-api-staging"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=staging"
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "patients-appointments-api-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "patients-appointments-api-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
image_repositories = []
