version = 0.1
[dev.deploy.parameters]
stack_name = "patients-appointments-api-dev"
resolve_s3 = true
s3_prefix = "patients-appointments-api-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = [] 